server:
  port: 8081
  context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  aop:
# aop默认开启(引入依赖后)，相当于主类上添加@EnableAspectJAutoProxy.
    auto: true
# 当需要使用CGLIB来实现AOP的时候，需要配置spring.aop.proxy-target-class=true，不然默认使用的是标准Java的实现
    spring.aop.proxy-target-class: false